language: php
php:
  - "5.6"
  - "7.0"
  - "7.1"
  - hhvm

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

env:

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp phpunit.xml.dist phpunit.xml


script:
  - phpunit

after_script:

# Customize when the notification emails are sent.
# notifications:
#     on_success: never
#     on_failure: always
